### ISSUE TITLE
Crash if back twice is pressed while downloading OCID data in map view

### ISSUE THREAD

**Issue by agilob** [CellularPrivacy/Android-IMSI-Catcher-Detector#851]
```
java.lang.RuntimeException: Unable to stop activity {com.SecUpwN.AIMSICD/com.secupwn.aimsicd.ui.activities.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3460)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3514)
at android.app.ActivityThread.access$1200(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:153)
at android.app.ActivityThread.main(ActivityThread.java:5071)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.secupwn.aimsicd.utils.RequestTask.showHideMapProgressBar(RequestTask.java:424)
at com.secupwn.aimsicd.utils.RequestTask.onActivityDetached(RequestTask.java:399)
at com.secupwn.aimsicd.utils.BaseAsyncTask.setActivity(BaseAsyncTask.java:30)
at com.secupwn.aimsicd.AndroidIMSICatcherDetector.detach(AndroidIMSICatcherDetector.java:110)
at com.secupwn.aimsicd.ui.activities.MainActivity.onStop(MainActivity.java:597)
at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1207)
at android.app.Activity.performStop(Activity.java:5401)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3455)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3514)
at android.app.ActivityThread.access$1200(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:153)
at android.app.ActivityThread.main(ActivityThread.java:5071)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by SecUpwN** [comment]
@mimi89999, would you please have a look at this and see if it is related to your recent fixes? Thanks!

**Comment by mimi89999** [comment]
I think that https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/commit/dfb88dafd6deb8c230139a795d1489bda664db38 fixed this issue.

@agilob Please build the latest version of AIMSICD and test this.

**Comment by agilob** [comment]
>@agilob Please build the latest version of AIMSICD and test this.

No, I this will wait for new release till I close it.

**Comment by mimi89999** [comment]
What?

**Comment by SecUpwN** [comment]
>No, I this will wait for new release till I close it.

@agilob, not cool. We're just trying to be supportive. I have justed added you to our `testing` team and thus you also have an invite to our `Buildozer` builds. Please use that bleeding edge APK to test this fix!

**Comment by Nordlenning** [comment]
I can not reproduce this with the latest fix

**Comment by mimi89999** [comment]
Please reopen this issue if you can reproduce it after my fix

**Comment by agilob** [comment]
>@agilob, not cool. We're just trying to be supportive.

No, you're asking a user to compile your code. You should be aware that doing it costs time and it's in not my interest to do it.

>What?

Good question, I think my touchpad marked and moved some words -.-'

**Comment by SecUpwN** [comment]
>No, you're asking a user to compile your code. You should be aware that doing it costs time and it's in not my interest to do it.

You don't even have to compile it yourself, `Buildozer` is doing that automatically for you.

>It also means apk will be singed with different key and I will lose data when installing new one.

We are developing here. So please do a backup of our release (freeze it) and test the bleeding edge.
