### ISSUE TITLE
NPE after clicking on tray notification

### ISSUE THREAD

**Issue by agilob** [CellularPrivacy/Android-IMSI-Catcher-Detector#871]
```
java.lang.NullPointerException
    at com.secupwn.aimsicd.ui.fragments.DeviceFragment.updateUI(DeviceFragment.java:132)
    at com.secupwn.aimsicd.ui.fragments.DeviceFragment.access$200(DeviceFragment.java:47)
    at com.secupwn.aimsicd.ui.fragments.DeviceFragment$1.onServiceConnected(DeviceFragment.java:109)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1097)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1114)
    at android.os.Handler.handleCallback(Handler.java:615)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:153)
    at android.app.ActivityThread.main(ActivityThread.java:5071)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
```

Trying to re-open app by clicking on notification. I'm also unable to reproduce it second time. Stack trace from Xposed cracker module.

**Comment by agilob** [comment]
ok got more meaningful stacktrace

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.SecUpwN.AIMSICD/com.secupwn.aimsicd.ui.activities.MainActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2225)
    at android.app.ActivityThread.access$600(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1301)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:153)
    at android.app.ActivityThread.main(ActivityThread.java:5071)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at com.secupwn.aimsicd.ui.fragments.MapFragment.onDestroyView(MapFragment.java:198)
    at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2167)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1141)
    at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1345)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:695)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
    at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
    at com.secupwn.aimsicd.ui.activities.MainActivity.onStart(MainActivity.java:586)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1166)
    at android.app.Activity.performStart(Activity.java:5257)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2225)
    at android.app.ActivityThread.access$600(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1301)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:153)
    at android.app.ActivityThread.main(ActivityThread.java:5071)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
```
