### ISSUE TITLE
AIMSICD crash in db view

### ISSUE THREAD

**Issue by Nordlenning** [CellularPrivacy/Android-IMSI-Catcher-Detector#890]
> Thank you for your feedback! Please add below details so that we can help you a bit faster.

---
#### Agreements

> Please check these boxes to ensure you've actually read and understood these important rules!
- [x ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---
#### Overview

> Please add a short and easy to understand description of the Issue you've experienced here.
- `AIMSICD` version (see the `About` screen): latest development branch; v0.1.43-alpha 
- Phone and ROM running _current_ release: CM 5.0.2
- Link to logfile without identifyable data:

E/AndroidRuntime(27937): FATAL EXCEPTION: main
E/AndroidRuntime(27937): Process: com.SecUpwN.AIMSICD, PID: 27937
E/AndroidRuntime(27937): java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
#### Reproduction

> Please tell us the detailed steps on how to reproduce your Issue here.

 Go into db-view push one tab, minimize AIMSICD maximize AIMSICD push another tab = crash. 
#### References

> If your Issue is related to any other existing Issues or pull requests, please link them here.

This happens with clean install before ocid key is downloaded.  
compiled after @Osteri  made fix on issue 888.  (07.07.16) (Solved & working fine)

EDIT: This was first reported in issue #870 as the 1'st issue & mentioned in issue 888

---
#### Screenshots

> If you experienced visual glitches, please add a screenshot without metadata here.

**Comment by Osteri** [comment]
Nice, although this has nothing to do with #888. I was also able to reproduce this:

```
RELEASE: 6.0.1
RESOURCES_SDK_INT: 23
SDK: 23
SDK_INT: 23
SECURITY_PATCH: 2016-03-01

Crash Information
Timestamp: July 2, 2016 4:46:23 PM GMT+03:00
Thread: Thread[main,5,main]
Stacktrace:
java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
    at io.realm.BaseRealm.checkIfValid(BaseRealm.java:437)
    at io.realm.RealmResults.isLoaded(RealmResults.java:872)
    at io.realm.RealmResults.size(RealmResults.java:371)
    at io.realm.RealmBaseAdapter.getCount(RealmBaseAdapter.java:98)
    at android.widget.ListView.onMeasure(ListView.java:1155)
    at android.view.View.measure(View.java:18796)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
    at android.view.View.measure(View.java:18796)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:18796)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
    at android.view.View.measure(View.java:18796)
    at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1075)
    at android.view.View.measure(View.java:18796)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
    at android.view.View.measure(View.java:18796)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:391)
    at android.view.View.measure(View.java:18796)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:18796)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
    at android.view.View.measure(View.java:18796)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2658)
    at android.view.View.measure(View.java:18796)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2108)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1224)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1460)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
    at android.view.Choreographer.doFrame(Choreographer.java:606)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5422)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
