### ISSUE TITLE
AIMSICD crash in db view -  BTS Measurements

### ISSUE THREAD

**Issue by Nordlenning** [CellularPrivacy/Android-IMSI-Catcher-Detector#903]
> Thank you for your feedback! Please add below details so that we can help you a bit faster.

---
#### Agreements

> Please check these boxes to ensure you've actually read and understood these important rules!
- [x ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---
#### Overview

> Please add a short and easy to understand description of the Issue you've experienced here.

Enter DB View, goto BTS Measurements, Scroll down the list fast = Crash
- `AIMSICD` version (see the `About` screen): v0.1.43-alpha-SNAPSHOT-normal-debug
- Phone and ROM running _current_ release: Sony Xperia V - CM  6.0.1
- Link to logfile without identifyable data:

--- System Information:
ACTIVE_CODENAMES: []
BASE_OS: 
CODENAME: REL
INCREMENTAL: 79c9f10fcc
PREVIEW_SDK_INT: 0
RELEASE: 6.0.1
RESOURCES_SDK_INT: 23
SDK: 23
SDK_INT: 23
SECURITY_PATCH: 2016-09-06

App Information:
APPLICATION_ID: com.SecUpwN.AIMSICD
BUILD_NUMBER: null
BUILD_TYPE: debug
DEBUG: true
FLAVOR: normal
GIT_SHA: 
OPEN_CELLID_API_KEY: NA
VERSION_CODE: 43
VERSION_NAME: v0.1.43-alpha-SNAPSHOT-normal-debug

Crash Information
Timestamp: October 13, 2016 3:13:23 AM GMT+02:00
Thread: Thread[main,5,main]
Stacktrace:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.secupwn.aimsicd.data.model.BaseTransceiverStation.getCellId()' on a null object reference
    at com.secupwn.aimsicd.adapters.MeasuredCellStrengthAdapter$ViewHolder.updateDisplay(MeasuredCellStrengthAdapter.java:73)
    at com.secupwn.aimsicd.adapters.MeasuredCellStrengthAdapter.getView(MeasuredCellStrengthAdapter.java:49)
    at android.widget.AbsListView.obtainView(AbsListView.java:2346)
    at android.widget.ListView.makeAndAddView(ListView.java:1876)
    at android.widget.ListView.fillDown(ListView.java:702)
    at android.widget.ListView.fillGap(ListView.java:666)
    at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5053)
    at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4601)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
    at android.view.Choreographer.doFrame(Choreographer.java:603)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
#### Reproduction

> Please tell us the detailed steps on how to reproduce your Issue here.

---Enter DB View, goto BTS Measurements, Scroll down the list fast = Crash
#### References

> If your Issue is related to any other existing Issues or pull requests, please link them here.

--- Not that I can find.
#### Screenshots

> If you experienced visual glitches, please add a screenshot without metadata here.

**Comment by Nordlenning** [comment]
I did some further test on this issue to and found that the speed of scroll has nothing to do with this.
The crash appears when you get down to  BTS Measurement nr 40, every time.
Scrolling down to 39 don't crash, but when I slowly pull up  BTS Measurement nr 40 it crash..every time.

Edit  After upgrading to CM 7.1.1 The crash appears when you scroll down to BTS Measurement nr 49
