### ISSUE TITLE
AIMSICD Crash in DB view

### ISSUE THREAD

**Issue by Nordlenning** [CellularPrivacy/Android-IMSI-Catcher-Detector#910]
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [x ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

* `AIMSICD` version (see the `About` screen): 0.1.43 SNAPSHOT-normal-debug
* Phone and ROM running *current* release: Sony Xperia V - CM 7.1.1
* logfile without identifyable data:

System Information:
ACTIVE_CODENAMES: []
BASE_OS: 
CODENAME: REL
INCREMENTAL: 2d28185a05
PREVIEW_SDK_INT: 0
RELEASE: 7.1.1
RESOURCES_SDK_INT: 25
SDK: 25
SDK_INT: 25
SECURITY_PATCH: 2016-12-05

App Information:
APPLICATION_ID: com.SecUpwN.AIMSICD
BUILD_NUMBER: null
BUILD_TYPE: debug
DEBUG: true
FLAVOR: normal
GIT_SHA: 
OPEN_CELLID_API_KEY: NA
VERSION_CODE: 43
VERSION_NAME:0.1.43 SNAPHOT-normal-debug.

Crash Information
Timestamp: December 10, 2016 1:51:11 PM GMT+01:00
Thread: Thread[main,5,main]
Stacktrace:
java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
	at io.realm.BaseRealm.checkIfValid(BaseRealm.java:437)
	at io.realm.RealmResults.isLoaded(RealmResults.java:872)
	at io.realm.RealmResults.size(RealmResults.java:371)
	at io.realm.RealmBaseAdapter.getCount(RealmBaseAdapter.java:98)
	at android.widget.ListView.layoutChildren(ListView.java:1617)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4021)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3814)
	at android.view.View.dispatchTouchEvent(View.java:10024)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
	at android.view.View.dispatchPointerEvent(View.java:10244)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6252)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6226)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6187)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6355)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6126)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

#### Reproduction
>Please tell us the detailed steps on how to reproduce your Issue here.

Go into DB view , go into current cell, minimice & maximice AIMSCID tap on anything in db view = Crash

#### References
>If your Issue is related to any other existing Issues or pull requests, please link them here.

No, This started after upgrading OS from CM 6.1.1 to CM 7.1.1

#### Screenshots
>If you experienced visual glitches, please add a screenshot without metadata here.

**Comment by Nordlenning** [comment]
Same as 890
