### ISSUE TITLE
Had constantly yellow icon 'BTS does not have neibouring cells' or 'BTS ID is unknown...'

### ISSUE THREAD

**Issue by sorcer1122** [CellularPrivacy/Android-IMSI-Catcher-Detector#912]
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [X ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [X ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [X ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

* `AIMSICD` version (see the `About` screen): v0.1.43-alpha-SNAPSHOT-normal-debug
* Phone and ROM running *current* release: Bluboo Picasso 3G (MTK6580), Android 5.1
* Link to logfile without identifyable data: http://pastebin.com/AVpMDB4p (this is from debugging menu in the app, not sure how useful it is).

---

#### Reproduction
>Please tell us the detailed steps on how to reproduce your Issue here.

I did a clean install on my friend's phone,enable persistent service in settings, input my API key and tried to download OCID db but was constantly getting timeout errors. Last night I finally managed to download OCID data and my icon immediately turned yellow saying that BTS does not have neighbouring cells or something like BTS ID is not in OCID database. I walked a bit around the area but the icon was constantly yellow.

A bit later I opened the app again, it crashed and when I re-opened it, the icon suddenly turned green again. At the moment it is still green. I am not sure how reliable this app is and why the icon was yellow and then suddenly green. There is a SIM card inside but no Internet, I only use wifi on the phone to download OCID db.

#### References
>If your Issue is related to any other existing Issues or pull requests, please link them here.

---

#### Screenshots
>If you experienced visual glitches, please add a screenshot without metadata here.

**Comment by mimi89999** [comment]
It was yellow because the station, that you were connected to was not on OpenCellId.

That crash is bad. Do you happen to have the log?

**Comment by sorcer1122** [comment]
Strange, isn't it? The icon went yellow AFTER I downloaded OCID db, which means BTS should be in there...and then suddenly the icon turned green.

I don't have any logs. Can I still get any from the phone?

**Comment by sorcer1122** [comment]
After another start I got yellow icon again saying Cell ID not in OpenCellId Database...

P.S. and now the yellow message is BTS doesn't provide any neighbour cells....interestingly, if I open Neighbouring Cells - I see a couple of BTS there.

**Comment by sorcer1122** [comment]
Tried it on two different phones and everywhere got a green icon. Any idea why is this?

**Comment by sorcer1122** [comment]
Occasionally the app crashes, I was able to get the following log:

System Information:
ACTIVE_CODENAMES: []
BASE_OS: 
CODENAME: REL
INCREMENTAL: 1474547917
RELEASE: 5.1
RESOURCES_SDK_INT: 22
SDK: 22
SDK_INT: 22
SECURITY_PATCH: 2016-06-01


App Information:
APPLICATION_ID: com.SecUpwN.AIMSICD
BUILD_NUMBER: null
BUILD_TYPE: debug
DEBUG: true
FLAVOR: normal
GIT_SHA: 05640ab
OPEN_CELLID_API_KEY: NA
VERSION_CODE: 43
VERSION_NAME: v0.1.43-alpha-SNAPSHOT-normal-debug


Crash Information
Timestamp: December 19, 2016 2:08:48 PM GMT+00:00
Thread: Thread[pool-2-thread-1,5,main]
Stacktrace:
java.lang.OutOfMemoryError: Failed to allocate a 16396 byte allocation with 3684 free bytes and 3KB until OOM
	at com.android.internal.util.FastXmlSerializer.<init>(FastXmlSerializer.java:55)
	at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:183)
	at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:597)
	at android.app.SharedPreferencesImpl.access$800(SharedPreferencesImpl.java:51)
	at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:512)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by tboneee44** [comment]
Hey! I have had similar problems with my AIMSICD software. When I try To load bts data or open my eventLog, applicatIin Crashes constantly. My phone have alerted "changing LAC" and "no neighbouring cells" over 1200 times in the last 24 hours. I managed To save Some screenshots and eventLogs before the programm Crashes,  but how do I put them here? :D
